container:
  image: node:latest

test_task:
  cubism_cache:
    folder: cubism
    fingerprint_script: git submodule status

    #https://github.com/cirruslabs/cirrus-ci-docs/issues/407
    populate_script:
      - git config --global url."https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/".insteadOf "git@github.com:"
      - git submodule init
      - git submodule update

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  core_cache:
    folder: core
    reupload_on_changes: false # normally the files will never change
    populate_script: yarn run setup

  test_script: yarn run test
